version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "michaelfuscoletti"
    assignees:
      - "michaelfuscoletti"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignore major version updates for stable packages
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:30"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "michaelfuscoletti"
    assignees:
      - "michaelfuscoletti"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
    ignore:
      # Ignore major version updates for React ecosystem
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react-dom"
        update-types: ["version-update:semver-major"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"
      day: "first-sunday"
      time: "03:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "michaelfuscoletti"
    assignees:
      - "michaelfuscoletti"
    commit-message:
      prefix: "chore(docker)"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "first-sunday"
      time: "02:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "michaelfuscoletti"
    assignees:
      - "michaelfuscoletti"
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "dependencies"
      - "github-actions"