# Production Override for Hetzner Deployment
# Use with: docker compose -f docker-compose.yml -f docker-compose.production.yml up -d

services:
  # Enable Caddy for production
  caddy:
    profiles:
      - 
    restart: always
    
  # Production API configuration
  api:
    restart: always
    environment:
      - ENVIRONMENT=production
      - DEBUG_MODE=false
      - CORS_ORIGINS=https://dock108.ai,https://www.dock108.ai
      
  # Production frontend build
  frontend:
    profiles:
      - build
    command: npm run build
    
  # Production-optimized Celery
  celery_worker:
    restart: always
    environment:
      - CELERY_CONCURRENCY=4
      
  celery_beat:
    restart: always
    
  # Production Redis with persistence
  redis:
    restart: always
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru