version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  celery:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(funcName)s:%(lineno)d | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  detailed:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(pathname)s:%(lineno)d | %(funcName)s() | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  celery_console:
    class: logging.StreamHandler
    level: INFO
    formatter: celery
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
  
  celery_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: celery
    filename: logs/celery.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  # Application loggers
  app:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  services:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  core:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  # Celery loggers
  celery:
    level: INFO
    handlers: [celery_console, celery_file]
    propagate: false
  
  celery.task:
    level: INFO
    handlers: [celery_console, celery_file]
    propagate: false
  
  celery.worker:
    level: INFO
    handlers: [celery_console, celery_file]
    propagate: false
  
  celery.beat:
    level: INFO
    handlers: [celery_console, celery_file]
    propagate: false
  
  # Third-party loggers (reduce noise)
  urllib3:
    level: WARNING
    handlers: [console]
    propagate: false
  
  requests:
    level: WARNING
    handlers: [console]
    propagate: false
  
  asyncio:
    level: WARNING
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console] 