version: 1
disable_existing_loggers: false

formatters:
  json:
    class: structlog.stdlib.ProcessorFormatter
    processor: structlog.processors.JSONRenderer
  
  standard:
    class: logging.Formatter
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: json
    filename: /app/logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    mode: a

loggers:
  # Application loggers
  app:
    level: INFO
    handlers: [console]
    propagate: no
  
  services:
    level: INFO
    handlers: [console]
    propagate: no
  
  core:
    level: INFO
    handlers: [console]
    propagate: no
  
  # FastAPI and uvicorn
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: no
  
  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: no
  
  fastapi:
    level: INFO
    handlers: [console]
    propagate: no
  
  # Celery
  celery:
    level: INFO
    handlers: [console]
    propagate: no
  
  # Database
  sqlalchemy:
    level: WARNING
    handlers: [console]
    propagate: no
  
  alembic:
    level: INFO
    handlers: [console]
    propagate: no
  
  # External libraries (reduce noise)
  httpx:
    level: WARNING
    handlers: [console]
    propagate: no
  
  requests:
    level: WARNING
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console] 